################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Set the FLINK_DOCKER_IMAGE_NAME environment variable to override the image name to use

version: "2.1"
services:
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
      - rabbitmq
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
      - "rabbitmq:rabbitmq"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  rabbitmq:
    image: rabbitmq:3.6

  influxdb:
    image: influxdb:1.4
    environment:
      - INFLUXDB_USER=gbfs
      - INFLUXDB_PASSWORD=gbfs
      - INFLUXDB_DB=gbfs

  gbfs-feed-consumer:
    image: skidder/gbfs-feed-consumer:latest
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
