version: "2.1"
services:
  jobmanager:
    image: flink:1.3.2-hadoop27-scala_2.11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.3.2-hadoop27-scala_2.11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
      - rabbitmq
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
      - "rabbitmq:rabbitmq"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  rabbitmq:
    image: rabbitmq:3.6

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  chronograf:
    image: chronograf:1.3
    ports:
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb

  kapacitor:
    image: kapacitor:1.3
    depends_on:
      - influxdb
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

  influxdb:
    image: influxdb:1.4
    environment:
      - INFLUXDB_USER=gbfs
      - INFLUXDB_PASSWORD=gbfs
      - INFLUXDB_DB=gbfs

  gbfs-feed-consumer:
    image: skidder/gbfs-feed-consumer:latest
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
